services:
  - type: web
    name: streaming-avatar-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /persona/config
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

